#test of using Pandas DataFrame as internal structure

Advantages
* well supported
* has connection to lots of I/O layers (even PyTables)
* can add/remove columns easily

Problems:
* can't seem to store vector data in a column...

In [26]:
import pandas as pd
import numpy as np

In [27]:
evid = np.arange(10) + 1024
X = np.linspace(-10,10,10, dtype=np.float32)
Y = np.linspace(-10,10,10, dtype=np.float32)
V = np.random.uniform(size=10)

In [28]:
data = pd.DataFrame({ 'DETX':X,'DETY':Y,'VALUE':V}, index=evid)
data

DETX       DETY     VALUE
1024 -10.000000 -10.000000  0.179955
1025  -7.777778  -7.777778  0.487733
1026  -5.555555  -5.555555  0.469597
1027  -3.333333  -3.333333  0.379217
1028  -1.111111  -1.111111  0.249932
1029   1.111112   1.111112  0.887062
1030   3.333334   3.333334  0.714865
1031   5.555556   5.555556  0.672744
1032   7.777779   7.777779  0.831903
1033  10.000000  10.000000  0.952904

In [29]:
data.describe()

DETX       DETY      VALUE
count  10.000000  10.000000  10.000000
mean    0.000000   0.000000   0.582591
std     6.728112   6.728112   0.269468
min   -10.000000 -10.000000   0.179955
25%    -5.000000  -5.000000   0.401812
50%     0.000000   0.000000   0.580238
75%     5.000001   5.000001   0.802643
max    10.000000  10.000000   0.952904

In [30]:
print data.loc[1029]

DETX     1.111112
DETY     1.111112
VALUE    0.887062
Name: 1029, dtype: float64


In [31]:
for col in data:
    print col

DETX
DETY
VALUE


Adding a column:

In [32]:
energy = np.random.lognormal(2,1,size=10)
data['ENERGY'] = energy
data

DETX       DETY     VALUE     ENERGY
1024 -10.000000 -10.000000  0.179955   9.194372
1025  -7.777778  -7.777778  0.487733   4.012506
1026  -5.555555  -5.555555  0.469597  11.690386
1027  -3.333333  -3.333333  0.379217  17.874603
1028  -1.111111  -1.111111  0.249932  11.729661
1029   1.111112   1.111112  0.887062   4.223501
1030   3.333334   3.333334  0.714865   2.725324
1031   5.555556   5.555556  0.672744   2.324606
1032   7.777779   7.777779  0.831903   1.538140
1033  10.000000  10.000000  0.952904   9.799554

adding array data:

In [40]:
pixval = np.arange(5*10).reshape(10,5)
print pixval
try:
    data['PIXVAL']=pixval
except Exception,e:
    print "FAILED:",e
data

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
FAILED: Wrong number of items passed 5, placement implies 1


DETX       DETY     VALUE     ENERGY
1024 -10.000000 -10.000000  0.179955   9.194372
1025  -7.777778  -7.777778  0.487733   4.012506
1026  -5.555555  -5.555555  0.469597  11.690386
1027  -3.333333  -3.333333  0.379217  17.874603
1028  -1.111111  -1.111111  0.249932  11.729661
1029   1.111112   1.111112  0.887062   4.223501
1030   3.333334   3.333334  0.714865   2.725324
1031   5.555556   5.555556  0.672744   2.324606
1032   7.777779   7.777779  0.831903   1.538140
1033  10.000000  10.000000  0.952904   9.799554